/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as BilletterieRouteImport } from './routes/billetterie'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as Hajj2027RouteImport } from './routes/hajj-2027'
import { Route as LocationVoitureRouteImport } from './routes/location-voiture'
import { Route as OmrasRouteImport } from './routes/omras'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SouvenirsRouteImport } from './routes/souvenirs'
import { Route as SudRouteImport } from './routes/sud'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const BilletterieRoute = BilletterieRouteImport.update({
  id: '/billetterie',
  path: '/billetterie',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const Hajj2027Route = Hajj2027RouteImport.update({
  id: '/hajj-2027',
  path: '/hajj-2027',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationVoitureRoute = LocationVoitureRouteImport.update({
  id: '/location-voiture',
  path: '/location-voiture',
  getParentRoute: () => rootRouteImport,
} as any)
const OmrasRoute = OmrasRouteImport.update({
  id: '/omras',
  path: '/omras',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SouvenirsRoute = SouvenirsRouteImport.update({
  id: '/souvenirs',
  path: '/souvenirs',
  getParentRoute: () => rootRouteImport,
} as any)
const SudRoute = SudRouteImport.update({
  id: '/sud',
  path: '/sud',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/billetterie': typeof BilletterieRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/hajj-2027': typeof Hajj2027Route
  '/location-voiture': typeof LocationVoitureRoute
  '/omras': typeof OmrasRoute
  '/services': typeof ServicesRoute
  '/souvenirs': typeof SouvenirsRoute
  '/sud': typeof SudRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/billetterie': typeof BilletterieRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/hajj-2027': typeof Hajj2027Route
  '/location-voiture': typeof LocationVoitureRoute
  '/omras': typeof OmrasRoute
  '/services': typeof ServicesRoute
  '/souvenirs': typeof SouvenirsRoute
  '/sud': typeof SudRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/billetterie': typeof BilletterieRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/hajj-2027': typeof Hajj2027Route
  '/location-voiture': typeof LocationVoitureRoute
  '/omras': typeof OmrasRoute
  '/services': typeof ServicesRoute
  '/souvenirs': typeof SouvenirsRoute
  '/sud': typeof SudRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/billetterie'
    | '/confidentialite'
    | '/contact'
    | '/cookies'
    | '/hajj-2027'
    | '/location-voiture'
    | '/omras'
    | '/services'
    | '/souvenirs'
    | '/sud'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/billetterie'
    | '/confidentialite'
    | '/contact'
    | '/cookies'
    | '/hajj-2027'
    | '/location-voiture'
    | '/omras'
    | '/services'
    | '/souvenirs'
    | '/sud'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/billetterie'
    | '/confidentialite'
    | '/contact'
    | '/cookies'
    | '/hajj-2027'
    | '/location-voiture'
    | '/omras'
    | '/services'
    | '/souvenirs'
    | '/sud'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  BilletterieRoute: typeof BilletterieRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  Hajj2027Route: typeof Hajj2027Route
  LocationVoitureRoute: typeof LocationVoitureRoute
  OmrasRoute: typeof OmrasRoute
  ServicesRoute: typeof ServicesRoute
  SouvenirsRoute: typeof SouvenirsRoute
  SudRoute: typeof SudRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billetterie': {
      id: '/billetterie'
      path: '/billetterie'
      fullPath: '/billetterie'
      preLoaderRoute: typeof BilletterieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hajj-2027': {
      id: '/hajj-2027'
      path: '/hajj-2027'
      fullPath: '/hajj-2027'
      preLoaderRoute: typeof Hajj2027RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location-voiture': {
      id: '/location-voiture'
      path: '/location-voiture'
      fullPath: '/location-voiture'
      preLoaderRoute: typeof LocationVoitureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/omras': {
      id: '/omras'
      path: '/omras'
      fullPath: '/omras'
      preLoaderRoute: typeof OmrasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/souvenirs': {
      id: '/souvenirs'
      path: '/souvenirs'
      fullPath: '/souvenirs'
      preLoaderRoute: typeof SouvenirsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sud': {
      id: '/sud'
      path: '/sud'
      fullPath: '/sud'
      preLoaderRoute: typeof SudRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  BilletterieRoute: BilletterieRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  Hajj2027Route: Hajj2027Route,
  LocationVoitureRoute: LocationVoitureRoute,
  OmrasRoute: OmrasRoute,
  ServicesRoute: ServicesRoute,
  SouvenirsRoute: SouvenirsRoute,
  SudRoute: SudRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
